=== moqui/moqui-framework/framework/xsd/rest-api-2.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
This software is in the public domain under CC0 1.0 Universal plus a
Grant of Patent License.

To the extent possible under law, the author(s) have dedicated all
copyright and related and neighboring rights to this software to the
public domain worldwide. This software is distributed without any
warranty.

You should have received a copy of the CC0 Public Domain Dedication
along with this software (see the LICENSE.md file). If not, see
<http://creativecommons.org/publicdomain/zero/1.0/>.
-->

<!-- NOTE: files using this schema are found in the service directory in a component when named *.rest.xml -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:include schemaLocation="common-types-2.1.xsd"/>

    <xs:element name="resource">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="method"/>
                <xs:element minOccurs="0" maxOccurs="1" ref="id"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="resource"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="displayName" type="xs:string"/>
            <xs:attribute name="description" type="xs:string"/>
            <xs:attribute name="version" type="xs:string"/>
            <xs:attribute name="require-authentication" type="authc-options" default="true"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="id">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="method"/>
                <xs:element minOccurs="0" maxOccurs="1" ref="id"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="resource"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="require-authentication" type="authc-options" default="true"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="method">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="1">
                <xs:element ref="service"/>
                <xs:element ref="entity"/>
            </xs:choice>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="get"/>
                        <xs:enumeration value="patch"/>
                        <xs:enumeration value="put"/>
                        <xs:enumeration value="post"/>
                        <xs:enumeration value="delete"/>
                        <xs:enumeration value="options"/>
                        <xs:enumeration value="head"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="require-authentication" type="authc-options" default="true"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="service">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="entity">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="masterName" type="xs:string">
                <xs:annotation><xs:documentation>
                    Name of the master definition applicable. There can be more than one
                    master definition. It is defined along with the entity definition.
                    Each master definition represents specific structure of the entity.
                </xs:documentation></xs:annotation>
            </xs:attribute>
            <xs:attribute name="operation" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="one"/>
                        <xs:enumeration value="list"/>
                        <xs:enumeration value="count"/>
                        <xs:enumeration value="create"/>
                        <xs:enumeration value="update"/>
                        <xs:enumeration value="store"/>
                        <xs:enumeration value="delete"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== moqui/moqui-framework/runtime/base-component/tools/service/moqui.rest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This software is in the public domain under CC0 1.0 Universal plus a
Grant of Patent License.

To the extent possible under law, the author(s) have dedicated all
copyright and related and neighboring rights to this software to the
public domain worldwide. This software is distributed without any
warranty.

You should have received a copy of the CC0 Public Domain Dedication
along with this software (see the LICENSE.md file). If not, see
<http://creativecommons.org/publicdomain/zero/1.0/>.
-->

<!-- General Guideline Verbs: GET=find, POST=create/do, PUT=store (create or update), PATCH=update, DELETE=delete  -->

<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://moqui.org/xsd/rest-api-2.1.xsd"
        name="moqui" displayName="Moqui Tools REST API" version="${moqui_version}"
        description="Services for various system administration and other tools in Moqui Framework. See more information
            about Moqui Framework at [http://www.moqui.org/framework](http://www.moqui.org/framework/index.html)">

    <resource name="artifacts" description="Artifacts - Screens, Services, Entities, etc">
        <resource name="hitSummary"><method type="get">
            <entity name="moqui.server.ArtifactHitReport" operation="list"/></method></resource>
        <resource name="hitBins"><method type="get">
            <entity name="moqui.server.ArtifactHitBin" operation="list"/></method></resource>
    </resource>

    <resource name="dataDocuments" description="Data Documents - Database derived JSON documents, feeds">
        <method type="get"><entity name="dataDocuments" operation="list"/></method>
        <method type="post"><entity name="dataDocuments" masterName="default" operation="create"/></method>
        <id name="dataDocumentId">
            <method type="get"><entity name="dataDocuments" masterName="default" operation="one"/></method>
            <method type="put"><entity name="dataDocuments" masterName="default" operation="update"/></method>
            <resource name="clone"><method type="post">
                <service name="org.moqui.impl.EntityServices.clone#DataDocument"/></method></resource>
        </id>
        <resource name="feeds">
            <id name="dataFeedId">
                <resource name="index"><method type="post">
                    <service name="org.moqui.search.SearchServices.index#DataFeedDocuments"/></method></resource>
                <resource name="documents"><method type="get">
                    <service name="org.moqui.impl.EntityServices.get#DataFeedDocuments"/></method></resource>
            </id>
        </resource>
        <resource name="indexes">
            <id name="indexName">
                <resource name="mappings"><method type="post">
                    <service name="org.moqui.search.SearchServices.put#DataDocumentMappings"/></method></resource>
                <resource name="search"><method type="post">
                    <service name="org.moqui.search.SearchServices.search#DataDocuments"/></method></resource>
                <!--
                <resource name="searchCount"><method type="post">
                    <service name="org.moqui.search.SearchServices.search#CountBySource"/></method></resource> -->
            </id>
        </resource>
    </resource>

    <resource name="basic" description="Basic Entities - Enum, Geo, Status, UOM, etc">
        <resource name="enums">
            <method type="get"><entity name="enums" operation="list"/></method>
            <method type="post"><entity name="enums" operation="create"/></method>
            <id name="enumId">
                <method type="get"><entity name="enums" masterName="default" operation="one"/></method>
                <method type="patch"><entity name="enums" operation="update"/></method>
            </id>
        </resource>
        <resource name="enumTypes">
            <method type="get"><entity name="moqui.basic.EnumerationType" operation="list"/></method>
            <id name="enumTypeId">
                <method type="get"><entity name="moqui.basic.EnumerationType" operation="one"/></method>
            </id>
        </resource>
        <resource name="geos">
            <method type="get"><entity name="geos" operation="list"/></method>
            <method type="post"><entity name="geos" operation="create"/></method>
            <id name="geoId">
                <method type="get"><entity name="geos" masterName="default" operation="one"/></method>
                <method type="patch"><entity name="geos" operation="update"/></method>
                <resource name="regions"><method type="get">
                    <service name="org.moqui.impl.BasicServices.get#GeoRegionsForDropDown"/></method></resource>
            </id>
        </resource>
        <resource name="statuses">
            <method type="get"><entity name="statuses" operation="list"/></method>
            <method type="post"><entity name="statuses" operation="create"/></method>
            <id name="statusId">
                <method type="get"><entity name="statuses" masterName="default" operation="one"/></method>
                <method type="patch"><entity name="statuses" operation="update"/></method>
            </id>
        </resource>
        <resource name="uoms">
            <method type="get"><entity name="uoms" operation="list"/></method>
            <method type="post"><entity name="uoms" operation="create"/></method>
            <id name="uomId">
                <method type="get"><entity name="uoms" masterName="default" operation="one"/></method>
                <method type="patch"><entity name="uoms" operation="update"/></method>
            </id>
        </resource>
    </resource>
    <resource name="email" description="Email Services - Messages, Templates, Servers">
        <resource name="messages">
            <method type="get"><entity name="emailMessages" operation="list"/></method>
            <!-- NOTE: for now no create allowed, created when sending or receiving -->
            <!-- <method type="post"><entity name="emailMessages" operation="create"/></method> -->
            <id name="emailMessageId">
                <method type="get"><entity name="emailMessages" masterName="default" operation="one"/></method>
                <method type="patch"><entity name="emailMessages" masterName="default" operation="update"/></method>
            </id>
        </resource>
        <resource name="templates">
            <method type="get"><entity name="emailTemplates" operation="list"/></method>
            <method type="post"><entity name="emailTemplates" operation="create"/></method>
            <id name="emailTemplateId">
                <method type="get"><entity name="emailTemplates" masterName="default" operation="one"/></method>
                <method type="patch"><entity name="emailTemplates" masterName="default" operation="update"/></method>
                <resource name="send"><method type="post">
                    <service name="org.moqui.impl.EmailServices.send#Email"/></method></resource>
            </id>
        </resource>
        <resource name="servers">
            <method type="get"><entity name="moqui.basic.email.EmailServer" operation="list"/></method>
            <method type="post"><entity name="moqui.basic.email.EmailServer" operation="create"/></method>
            <id name="emailServerId">
                <method type="get"><entity name="moqui.basic.email.EmailServer" operation="one"/></method>
                <method type="patch"><entity name="moqui.basic.email.EmailServer" operation="update"/></method>
                <resource name="poll"><method type="post">
                    <service name="org.moqui.impl.EmailServices.poll#EmailServer"/></method></resource>
            </id>
        </resource>
    </resource>
    <resource name="print" description="Print - Network Printers and Jobs">
        <resource name="printers">
            <method type="get"><entity name="moqui.basic.print.NetworkPrinter" operation="list"/></method>
            <method type="post"><entity name="moqui.basic.print.NetworkPrinter" operation="create"/></method>
            <id name="networkPrinterId">
                <method type="get"><entity name="moqui.basic.print.NetworkPrinter" operation="one"/></method>
                <method type="patch"><entity name="moqui.basic.print.NetworkPrinter" operation="update"/></method>

                <resource name="print">
                    <!-- TODO how to handle InputStream or SerialBlob in parameters? -->
                    <resource name="document"><method type="post">
                        <service name="org.moqui.impl.PrintServices.print#Document"/></method></resource>
                    <resource name="resource"><method type="post">
                        <service name="org.moqui.impl.PrintServices.print#ResourceDocument"/></method></resource>
                    <resource name="screen"><method type="post">
                        <service name="org.moqui.impl.PrintServices.print#ScreenDocument"/></method></resource>
                </resource>
            </id>
        </resource>
        <resource name="jobs">
            <method type="get"><entity name="printJobs" operation="list"/></method>
            <method type="post"><entity name="printJobs" operation="create"/></method>

            <id name="printJobId">
                <method type="get"><entity name="printJobs" masterName="default" operation="one"/></method>
                <method type="patch"><entity name="printJobs" operation="update"/></method>

                <resource name="send"><method type="post">
                    <service name="org.moqui.impl.PrintServices.send#PrintJob"/></method></resource>
                <resource name="serverDetails"><method type="get">
